"""empty message

Revision ID: 026b8bb70637
Revises: 9724d9871890
Create Date: 2017-06-08 20:59:53.142674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '026b8bb70637'
down_revision = '9724d9871890'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bucketlists', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'bucketlists', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bucketlists', type_='foreignkey')
    op.drop_column('bucketlists', 'created_by')
    # ### end Alembic commands ###
